version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 18
        commands:
            - echo Installing Node.js
            - node --version
            - npm --version

    pre_build:
        commands:
            - echo Installing dependencies
            - npm ci --prefer-offline --no-audit

    build:
        commands:
            - echo Build started on `date`
            - echo Building Angular application
            - npm run build -- --configuration=production
            - echo Build completed on `date`
            - ls -la dist/
            - ls -la dist/booster-ng/

    post_build:
        commands:
            - echo Post-build phase
            - echo Build artifacts ready

artifacts:
    files:
        - '**/*'
    base-directory: 'dist/booster-ng'
    discard-paths: no

cache:
    paths:
        - 'node_modules/**/*'
